-- VTA Marketplace foundation. Run after the existing CMS migrations.
create extension if not exists pgcrypto;
create type public.app_role as enum ('master_admin','industry_member','user');
create type public.member_verification_status as enum ('pending','under_review','verified','rejected','suspended');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, phone text, role app_role not null default 'user', account_status text not null default 'active' check(account_status in ('active','pending','suspended','blocked')), avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.industry_members (id uuid primary key default gen_random_uuid(), user_id uuid unique not null references auth.users(id), organization_name text not null, slug text unique not null, organization_type text, short_description text, full_description text, logo_url text, banner_url text, website text, business_email text, business_phone text, alternate_phone text, address_line_1 text, address_line_2 text, city text, district text, state text, postal_code text, country text default 'India', latitude numeric, longitude numeric, year_established int, employee_count_range text, annual_turnover_range text, gst_number text, cin_number text, udyam_number text, iec_number text, pan_number text, is_exporter boolean default false, export_markets text[] default '{}', product_categories text[] default '{}', materials text[] default '{}', techniques text[] default '{}', certifications text[] default '{}', manufacturing_capabilities text[] default '{}', business_hours jsonb default '{}', social_links jsonb default '{}', verification_status member_verification_status not null default 'pending', verification_notes text, verified_by uuid references auth.users(id), verified_at timestamptz, rejection_reason text, suspended_at timestamptz, suspension_reason text, profile_completion int default 0 check(profile_completion between 0 and 100), is_featured boolean default false, is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.industry_member_documents (id uuid primary key default gen_random_uuid(), industry_member_id uuid not null references industry_members(id) on delete cascade, document_type text not null, document_name text not null, document_url text not null, document_number text, verification_status text default 'pending', review_notes text, verified_by uuid references auth.users(id), verified_at timestamptz, is_public boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.marketplace_categories (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, icon text, image_url text, parent_id uuid references marketplace_categories(id), sort_order int default 0, is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.marketplace_products (id uuid primary key default gen_random_uuid(), industry_member_id uuid not null references industry_members(id), category_id uuid references marketplace_categories(id), name text not null, slug text unique not null, sku text, short_description text, full_description text, product_type text, material text, materials text[] default '{}', technique text, techniques text[] default '{}', weave_type text, dyeing_method text, pattern text, motifs text[] default '{}', color_options text[] default '{}', size_options text[] default '{}', product_form text, origin_state text, origin_city text, gi_tagged boolean default false, gi_name text, certifications text[] default '{}', sustainability_attributes text[] default '{}', minimum_order_quantity numeric check(minimum_order_quantity>=0), moq_unit text, production_capacity text, lead_time_days int check(lead_time_days>=0), sample_available boolean default false, customization_available boolean default false, private_label_available boolean default false, export_available boolean default false, domestic_shipping_available boolean default true, pricing_type text default 'on_request' check(pricing_type in ('on_request','fixed','range','negotiable')), indicative_price_min numeric check(indicative_price_min>=0), indicative_price_max numeric check(indicative_price_max>=0), currency text default 'INR', price_unit text, primary_image_url text, video_url text, status text default 'draft' check(status in ('draft','submitted','published','unpublished','archived','rejected')), moderation_status text default 'not_submitted' check(moderation_status in ('not_submitted','pending_review','approved','rejected')), moderation_notes text, is_featured boolean default false, view_count bigint default 0, enquiry_count bigint default 0, published_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz, search_vector tsvector generated always as (to_tsvector('english',coalesce(name,'')||' '||coalesce(short_description,'')||' '||coalesce(material,''))) stored, check(indicative_price_max is null or indicative_price_min is null or indicative_price_max>=indicative_price_min));
create table public.marketplace_product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references marketplace_products(id) on delete cascade, image_url text not null, alt_text text, caption text, sort_order int default 0, is_primary boolean default false, created_at timestamptz default now());
create table public.marketplace_product_specifications (id uuid primary key default gen_random_uuid(), product_id uuid not null references marketplace_products(id) on delete cascade, specification_name text not null, specification_value text not null, unit text, sort_order int default 0, created_at timestamptz default now());
create table public.marketplace_product_documents (id uuid primary key default gen_random_uuid(), product_id uuid not null references marketplace_products(id) on delete cascade, document_type text, document_name text not null, document_url text not null, is_public boolean default false, created_at timestamptz default now());
create table public.saved_marketplace_products (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, product_id uuid not null references marketplace_products(id) on delete cascade, created_at timestamptz default now(), unique(user_id,product_id));
create sequence public.marketplace_enquiry_seq; create sequence public.marketplace_quotation_seq;
create table public.marketplace_enquiries (id uuid primary key default gen_random_uuid(), enquiry_number text unique default ('VTA-RFQ-'||extract(year from now())::int||'-'||lpad(nextval('marketplace_enquiry_seq')::text,6,'0')), user_id uuid not null references auth.users(id), industry_member_id uuid not null references industry_members(id), product_id uuid references marketplace_products(id), enquiry_type text not null default 'general', subject text not null, requirement_description text not null, quantity numeric check(quantity>0), quantity_unit text, target_price numeric check(target_price>=0), currency text default 'INR', delivery_city text, delivery_state text, delivery_country text default 'India', expected_delivery_date date, customization_required boolean default false, sample_required boolean default false, attachment_urls text[] default '{}', buyer_name text, buyer_company text, buyer_email text, buyer_phone text, status text default 'new', priority text default 'normal', last_message_at timestamptz default now(), closed_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.marketplace_enquiry_messages (id uuid primary key default gen_random_uuid(), enquiry_id uuid not null references marketplace_enquiries(id) on delete cascade, sender_user_id uuid not null references auth.users(id), sender_role app_role, message text not null check(length(trim(message))>0), attachment_urls text[] default '{}', is_internal_note boolean default false, read_at timestamptz, created_at timestamptz default now());
create table public.marketplace_quotations (id uuid primary key default gen_random_uuid(), quotation_number text unique default ('VTA-QTN-'||extract(year from now())::int||'-'||lpad(nextval('marketplace_quotation_seq')::text,6,'0')), enquiry_id uuid not null references marketplace_enquiries(id), industry_member_id uuid not null references industry_members(id), user_id uuid not null references auth.users(id), version int default 1, status text default 'draft', currency text default 'INR', subtotal numeric default 0, discount_type text, discount_value numeric default 0, discount_amount numeric default 0, tax_amount numeric default 0, shipping_amount numeric default 0, other_charges numeric default 0, grand_total numeric default 0, valid_until date, payment_terms text, delivery_terms text, delivery_timeline text, shipping_terms text, warranty_terms text, notes text, terms_and_conditions text, quotation_pdf_url text, parent_quotation_id uuid references marketplace_quotations(id), sent_at timestamptz, viewed_at timestamptz, accepted_at timestamptz, rejected_at timestamptz, rejection_reason text, revision_request text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(enquiry_id,version));
create table public.marketplace_quotation_items (id uuid primary key default gen_random_uuid(), quotation_id uuid not null references marketplace_quotations(id) on delete cascade, product_id uuid references marketplace_products(id), item_name text not null, description text, quantity numeric not null check(quantity>0), unit text, unit_price numeric not null check(unit_price>=0), tax_rate numeric default 0, tax_amount numeric default 0, discount_amount numeric default 0, line_total numeric not null check(line_total>=0), sort_order int default 0, created_at timestamptz default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, type text not null, title text not null, message text, entity_type text, entity_id uuid, action_url text, is_read boolean default false, created_at timestamptz default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_user_id uuid references auth.users(id), actor_role app_role, action text not null, entity_type text not null, entity_id uuid, old_values jsonb, new_values jsonb, ip_address inet, user_agent text, created_at timestamptz default now());

create or replace function public.get_current_app_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles as p
  where p.id = auth.uid()
$$;

create or replace function public.is_master_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.get_current_app_role() = 'master_admin'::public.app_role, false)
$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into profiles(id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email); return new; end$$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
do $$declare t text; begin foreach t in array array['profiles','industry_members','industry_member_documents','marketplace_categories','marketplace_products','marketplace_enquiries','marketplace_quotations'] loop execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',t); end loop; end$$;

alter table profiles enable row level security; alter table industry_members enable row level security; alter table industry_member_documents enable row level security; alter table marketplace_categories enable row level security; alter table marketplace_products enable row level security; alter table marketplace_product_images enable row level security; alter table marketplace_product_specifications enable row level security; alter table marketplace_product_documents enable row level security; alter table saved_marketplace_products enable row level security; alter table marketplace_enquiries enable row level security; alter table marketplace_enquiry_messages enable row level security; alter table marketplace_quotations enable row level security; alter table marketplace_quotation_items enable row level security; alter table notifications enable row level security; alter table audit_logs enable row level security;
create policy profiles_self_read on profiles for select using(id=auth.uid() or is_master_admin()); create policy profiles_self_update on profiles for update using(id=auth.uid()) with check(id=auth.uid() and role=(select p.role from profiles p where p.id=auth.uid()));
create policy categories_public_read on marketplace_categories for select using(is_active or is_master_admin()); create policy categories_admin_all on marketplace_categories for all using(is_master_admin()) with check(is_master_admin());
create policy members_public_read on industry_members for select using((verification_status='verified' and is_active) or user_id=auth.uid() or is_master_admin()); create policy members_owner_update on industry_members for update using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy members_admin_all on industry_members for all using(is_master_admin()) with check(is_master_admin());
create policy products_public_read on marketplace_products for select using((status='published' and exists(select 1 from industry_members m where m.id=industry_member_id and m.verification_status='verified' and m.is_active)) or exists(select 1 from industry_members m where m.id=industry_member_id and m.user_id=auth.uid()) or is_master_admin());
create policy products_owner_write on marketplace_products for all using(exists(select 1 from industry_members m where m.id=industry_member_id and m.user_id=auth.uid())) with check(exists(select 1 from industry_members m where m.id=industry_member_id and m.user_id=auth.uid() and (status<>'published' or m.verification_status='verified'))); create policy products_admin_all on marketplace_products for all using(is_master_admin()) with check(is_master_admin());
create policy product_children_read on marketplace_product_images for select using(exists(select 1 from marketplace_products p where p.id=product_id)); create policy product_specs_read on marketplace_product_specifications for select using(exists(select 1 from marketplace_products p where p.id=product_id)); create policy public_product_docs on marketplace_product_documents for select using(is_public and exists(select 1 from marketplace_products p where p.id=product_id));
create policy saved_owner_all on saved_marketplace_products for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy enquiry_participants_read on marketplace_enquiries for select using(user_id=auth.uid() or exists(select 1 from industry_members m where m.id=industry_member_id and m.user_id=auth.uid()) or is_master_admin()); create policy enquiry_buyer_insert on marketplace_enquiries for insert with check(user_id=auth.uid()); create policy enquiry_participant_update on marketplace_enquiries for update using(user_id=auth.uid() or exists(select 1 from industry_members m where m.id=industry_member_id and m.user_id=auth.uid()) or is_master_admin());
create policy messages_participants_read on marketplace_enquiry_messages for select using((not is_internal_note or is_master_admin()) and exists(select 1 from marketplace_enquiries e left join industry_members m on m.id=e.industry_member_id where e.id=enquiry_id and (e.user_id=auth.uid() or m.user_id=auth.uid() or is_master_admin()))); create policy messages_participant_insert on marketplace_enquiry_messages for insert with check(sender_user_id=auth.uid() and (not is_internal_note or is_master_admin()) and exists(select 1 from marketplace_enquiries e left join industry_members m on m.id=e.industry_member_id where e.id=enquiry_id and (e.user_id=auth.uid() or m.user_id=auth.uid() or is_master_admin())));
create policy quotations_participants_read on marketplace_quotations for select using(user_id=auth.uid() or exists(select 1 from industry_members m where m.id=industry_member_id and m.user_id=auth.uid()) or is_master_admin()); create policy quotation_items_participants on marketplace_quotation_items for select using(exists(select 1 from marketplace_quotations q where q.id=quotation_id));
create policy notifications_owner on notifications for select using(user_id=auth.uid() or is_master_admin()); create policy notifications_owner_update on notifications for update using(user_id=auth.uid()); create policy audit_admin_read on audit_logs for select using(is_master_admin());

create index marketplace_products_search_idx on marketplace_products using gin(search_vector); create index marketplace_products_filter_idx on marketplace_products(status,category_id,origin_state,published_at desc); create index marketplace_products_member_idx on marketplace_products(industry_member_id); create index enquiries_user_idx on marketplace_enquiries(user_id,created_at desc); create index enquiries_member_idx on marketplace_enquiries(industry_member_id,status,last_message_at desc); create index messages_enquiry_idx on marketplace_enquiry_messages(enquiry_id,created_at); create index quotations_user_idx on marketplace_quotations(user_id,created_at desc); create index notifications_user_idx on notifications(user_id,is_read,created_at desc);

insert into storage.buckets(id,name,public) values ('marketplace-products','marketplace-products',true),('member-branding','member-branding',true),('member-gallery','member-gallery',true),('marketplace-documents','marketplace-documents',false),('enquiry-attachments','enquiry-attachments',false),('quotation-documents','quotation-documents',false),('member-verification-documents','member-verification-documents',false) on conflict(id) do nothing;
create policy public_marketplace_assets on storage.objects for select using(bucket_id in ('marketplace-products','member-branding','member-gallery')); create policy authenticated_owner_upload on storage.objects for insert to authenticated with check((storage.foldername(name))[1]=auth.uid()::text and bucket_id in ('marketplace-products','member-branding','member-gallery','marketplace-documents','enquiry-attachments','quotation-documents','member-verification-documents')); create policy owner_storage_manage on storage.objects for update to authenticated using((storage.foldername(name))[1]=auth.uid()::text); create policy owner_storage_delete on storage.objects for delete to authenticated using((storage.foldername(name))[1]=auth.uid()::text);

insert into marketplace_categories(name,slug,sort_order) values ('Sarees','sarees',1),('Fabrics','fabrics',2),('Yarn','yarn',3),('Garments','garments',4),('Home Textiles','home-textiles',5),('Carpets and Rugs','carpets-rugs',6),('Handloom Products','handloom-products',7),('Technical Textiles','technical-textiles',8),('Textile Machinery','textile-machinery',9),('Dyes and Chemicals','dyes-chemicals',10),('Textile Services','textile-services',11) on conflict(slug) do nothing;
