import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheckCircle, faLeaf, faLocationDot, faBox, faIndianRupeeSign } from '@fortawesome/free-solid-svg-icons';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
export const VerifiedBadge=()=> <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700"><FontAwesomeIcon icon={faCheckCircle}/> Verified</span>;
export const StatusBadge=({status='unknown'})=><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-700">{status.replaceAll('_',' ')}</span>;
export function PriceDisplay({product}){if(product.pricing_type==='on_request')return <span className="font-bold text-primary-700">Price on request</span>;return <span className="font-bold text-slate-900"><FontAwesomeIcon icon={faIndianRupeeSign}/> {Number(product.indicative_price_min||0).toLocaleString('en-IN')}{product.indicative_price_max?` – ${Number(product.indicative_price_max).toLocaleString('en-IN')}`:''} / {product.price_unit||'unit'}</span>}
export function ProductCard({product}){return <motion.article whileHover={{y:-6}} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><Link to={`/marketplace/products/${product.slug}`}><div className="aspect-[4/3] bg-slate-100"><img src={product.primary_image_url||'/assets/textiles/banarasi_silk.png'} alt={product.name} className="h-full w-full object-cover"/></div><div className="p-5"><div className="mb-3 flex items-center justify-between gap-2">{product.gi_tagged?<span className="text-xs font-bold text-amber-700"><FontAwesomeIcon icon={faLeaf}/> GI tagged</span>:<span/>}<VerifiedBadge/></div><h3 className="text-lg font-extrabold text-slate-900">{product.name}</h3><p className="mt-1 line-clamp-2 text-sm text-slate-600">{product.short_description}</p><div className="mt-4"><PriceDisplay product={product}/></div><div className="mt-4 flex justify-between text-xs text-slate-500"><span><FontAwesomeIcon icon={faBox}/> MOQ {product.minimum_order_quantity||'—'} {product.moq_unit||''}</span><span><FontAwesomeIcon icon={faLocationDot}/> {product.origin_state||'India'}</span></div></div></Link></motion.article>}
export const LoadingSkeleton=()=> <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map(i=><div key={i} className="h-96 animate-pulse rounded-3xl bg-slate-200"/>)}</div>;
export const EmptyState=({title='Nothing here yet',message='Try changing your filters.'})=><div className="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 text-slate-500">{message}</p></div>;
export const ErrorState=({message,retry})=><div className="rounded-3xl bg-red-50 p-8 text-center text-red-800"><p>{message||'Something went wrong.'}</p>{retry&&<button className="mt-4 font-bold underline" onClick={retry}>Try again</button>}</div>;
