import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';

const emptyForm={name:'',slug:'',short_description:'',material:'',category_id:'',minimum_order_quantity:'',moq_unit:'pieces',pricing_type:'on_request'};
function Shell({children,open}){const auth=useAuth();return <main data-lenis-prevent className="min-h-screen bg-slate-50"><header className="bg-slate-950 text-white"><div className="section-container flex flex-wrap items-center justify-between gap-4 py-5"><Link to="/member" className="font-black">VTA Partner Portal</Link><nav className="flex gap-4 text-sm font-bold text-slate-300"><Link to="/member">Overview</Link><Link to="/member/enquiries">Enquiries</Link><Link to="/member/quotations">Quotations</Link><Link to="/member/profile">Company profile</Link></nav><button onClick={auth.signOut}>Sign out</button></div></header><section className="section-container py-10"><div className="flex justify-between"><div><h1 className="text-3xl font-black">Products</h1><p className="mt-2 text-slate-500">Create buyer-ready product listings with an image.</p></div><button onClick={open} className="btn-primary">Add product</button></div>{children}</section></main>}
const Status=({value})=><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold capitalize">{(value||'').replaceAll('_',' ')}</span>;

export default function PartnerProducts(){
 const auth=useAuth(),[rows,setRows]=useState([]),[categories,setCategories]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(emptyForm),[image,setImage]=useState(null),[preview,setPreview]=useState('');
 const load=useCallback(async()=>{if(!auth.memberProfile?.id)return;setLoading(true);try{const [p,c]=await Promise.all([supabase.from('marketplace_products').select('*,marketplace_categories(name)').eq('industry_member_id',auth.memberProfile.id).order('updated_at',{ascending:false}),supabase.from('marketplace_categories').select('id,name').eq('is_active',true).order('sort_order')]);if(p.error)throw p.error;if(c.error)throw c.error;setRows(p.data||[]);setCategories(c.data||[]);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}},[auth.memberProfile?.id]);
 useEffect(()=>{load()},[load]);useEffect(()=>{if(!image){setPreview('');return}const url=URL.createObjectURL(image);setPreview(url);return()=>URL.revokeObjectURL(url)},[image]);
 const chooseImage=e=>{const file=e.target.files?.[0];setError('');if(!file)return setImage(null);if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){e.target.value='';return setError('Use a JPG, PNG, or WebP image no larger than 8 MB.')}setImage(file)};
 const save=async e=>{e.preventDefault();if(!image)return setError('Please upload a product image.');setSaving(true);setError('');let path='';try{const ext=image.name.split('.').pop()?.toLowerCase()||'jpg';path=`${auth.user.id}/products/${crypto.randomUUID()}.${ext}`;const uploaded=await supabase.storage.from('marketplace-products').upload(path,image,{contentType:image.type});if(uploaded.error)throw uploaded.error;const {data:url}=supabase.storage.from('marketplace-products').getPublicUrl(path);const result=await supabase.from('marketplace_products').insert({...form,industry_member_id:auth.memberProfile.id,slug:form.slug||`${form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${Date.now().toString().slice(-5)}`,minimum_order_quantity:form.minimum_order_quantity?Number(form.minimum_order_quantity):null,primary_image_url:url.publicUrl,status:'draft',moderation_status:'not_submitted'});if(result.error)throw result.error;setOpen(false);setForm(emptyForm);setImage(null);await load()}catch(err){if(path)await supabase.storage.from('marketplace-products').remove([path]);setError(err.message)}finally{setSaving(false)}};
 const submit=async row=>{const result=await supabase.from('marketplace_products').update({status:'submitted',moderation_status:'pending_review'}).eq('id',row.id);if(result.error)setError(result.error.message);else load()};
 return <Shell open={()=>setOpen(true)}>{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{loading?<p className="p-10 text-center">Loading…</p>:<div className="mt-7 grid gap-4">{rows.map(row=><article key={row.id} className="flex flex-col gap-4 rounded-2xl border bg-white p-4 sm:flex-row sm:items-center"><img src={row.primary_image_url} alt="" className="h-24 w-28 rounded-xl bg-slate-100 object-cover"/><div className="flex-1"><b>{row.name}</b><p className="text-sm text-slate-500">{row.marketplace_categories?.name||'Uncategorised'} · {row.material||'—'}</p><div className="mt-2 flex gap-2"><Status value={row.status}/><Status value={row.moderation_status}/></div></div>{row.status==='draft'&&<button onClick={()=>submit(row)} className="font-bold text-primary-700">Submit for review</button>}</article>)}{!rows.length&&<p className="rounded-2xl border bg-white p-10 text-center text-slate-500">No products yet.</p>}</div>}{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form data-lenis-prevent onSubmit={save} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-7"><div className="flex justify-between"><h2 className="text-2xl font-black">New product draft</h2><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-xs font-bold uppercase">Product image *<input required type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage} className="mt-1 w-full rounded-xl border p-3 text-sm normal-case"/></label>{preview&&<img src={preview} alt="Preview" className="sm:col-span-2 max-h-64 w-full rounded-2xl object-contain"/>}{[['Product name','name'],['Custom slug','slug'],['Material','material'],['MOQ','minimum_order_quantity'],['MOQ unit','moq_unit']].map(([label,key])=><label key={key} className="text-xs font-bold uppercase">{label}<input required={key==='name'} value={form[key]} onChange={ev=>setForm({...form,[key]:ev.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label>)}<label className="text-xs font-bold uppercase">Category<select value={form.category_id} onChange={ev=>setForm({...form,category_id:ev.target.value})} className="mt-1 w-full rounded-xl border p-3"><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="sm:col-span-2 text-xs font-bold uppercase">Description<textarea required rows="4" value={form.short_description} onChange={ev=>setForm({...form,short_description:ev.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-5 py-3 font-bold">Cancel</button><button disabled={saving} className="btn-primary">{saving?'Uploading…':'Save draft'}</button></div></form></div>}</Shell>}
