import { useCallback, useEffect, useMemo, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBuilding, faCheck, faEye, faPlus, faRotate, faSearch, faUser, faXmark } from '@fortawesome/free-solid-svg-icons';
import { supabase } from '../lib/supabase';
import AccountCreateModal from './AccountCreateModal';

const badge = { verified:'bg-emerald-100 text-emerald-700', pending:'bg-amber-100 text-amber-700', under_review:'bg-blue-100 text-blue-700', rejected:'bg-red-100 text-red-700', suspended:'bg-slate-200 text-slate-700' };
export default function AdminAccountRegistry(){
  const [tab,setTab]=useState('industry'),[members,setMembers]=useState([]),[buyers,setBuyers]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[createOpen,setCreateOpen]=useState(false),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [{data:memberData,error:memberError},{data:buyerData,error:buyerError}]=await Promise.all([supabase.from('industry_members').select('*,industry_member_documents(*)').order('created_at',{ascending:false}),supabase.from('profiles').select('*').eq('role','user').order('created_at',{ascending:false})]);if(memberError)throw memberError;if(buyerError)throw buyerError;const ids=(memberData||[]).map(m=>m.user_id);let profiles=[];if(ids.length){const {data,error:profilesError}=await supabase.from('profiles').select('*').in('id',ids);if(profilesError)throw profilesError;profiles=data||[];}setMembers((memberData||[]).map(m=>({...m,profile:profiles.find(p=>p.id===m.user_id)})));setBuyers(buyerData||[]);}catch(e){setError(e.message);}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const rows=useMemo(()=>{const source=tab==='industry'?members:buyers,term=search.toLowerCase();return source.filter(row=>JSON.stringify(row).toLowerCase().includes(term))},[tab,members,buyers,search]);
  const review=async(status)=>{let reason=null;if(['rejected','suspended'].includes(status)){reason=window.prompt(`Reason for ${status}:`);if(!reason?.trim())return;}setBusy(true);const rpc=tab==='industry'?'admin_review_industry_member':'admin_review_buyer';const args=tab==='industry'?{target_member_id:selected.id,next_status:status,review_reason:reason}:{target_user_id:selected.id,next_status:status,review_reason:reason};const {error:rpcError}=await supabase.rpc(rpc,args);setBusy(false);if(rpcError){setError(rpcError.message);return;}setSelected(null);load();};
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-black text-slate-900">Member & Buyer Registry</h1><p className="mt-1 text-sm text-slate-500">Verify identities, review applications and control marketplace access.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold"><FontAwesomeIcon icon={faRotate}/> Refresh</button><button onClick={()=>setCreateOpen(true)} className="rounded-xl bg-primary-600 px-4 py-2 text-sm font-bold text-white"><FontAwesomeIcon icon={faPlus}/> Create account</button></div></div>{createOpen&&<AccountCreateModal onClose={()=>setCreateOpen(false)} onCreated={load}/>} 
  <div className="mt-7 flex gap-2 border-b"><button onClick={()=>setTab('industry')} className={`px-5 py-3 text-sm font-bold ${tab==='industry'?'border-b-2 border-primary-600 text-primary-700':'text-slate-500'}`}><FontAwesomeIcon icon={faBuilding}/> Industry Partners <span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5">{members.length}</span></button><button onClick={()=>setTab('buyers')} className={`px-5 py-3 text-sm font-bold ${tab==='buyers'?'border-b-2 border-primary-600 text-primary-700':'text-slate-500'}`}><FontAwesomeIcon icon={faUser}/> Buyers <span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5">{buyers.length}</span></button></div>
  <label className="mt-5 flex max-w-md items-center gap-3 rounded-xl border bg-white px-4"><FontAwesomeIcon icon={faSearch} className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full py-3 outline-none" placeholder="Search name, email, company or state"/></label>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
  <div className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<p className="p-10 text-center text-slate-500">Loading registry…</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Identity</th><th className="px-5 py-4">Location / Type</th><th className="px-5 py-4">Submitted</th><th className="px-5 py-4">Verification</th><th className="px-5 py-4"></th></tr></thead><tbody className="divide-y">{rows.map(row=>{const status=tab==='industry'?row.verification_status:row.buyer_verification_status;return <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-4"><b className="block text-slate-900">{tab==='industry'?row.organization_name:row.full_name||'Unnamed buyer'}</b><span className="text-slate-500">{tab==='industry'?row.profile?.email:row.email}</span></td><td className="px-5 py-4 text-slate-600">{tab==='industry'?[row.city,row.state].filter(Boolean).join(', ')||'—':row.company_name||[row.city,row.state].filter(Boolean).join(', ')||'Individual buyer'}</td><td className="px-5 py-4 text-slate-500">{new Date(row.created_at).toLocaleDateString('en-IN')}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${badge[status]||badge.pending}`}>{(status||'pending').replaceAll('_',' ')}</span></td><td className="px-5 py-4 text-right"><button onClick={()=>setSelected(row)} className="rounded-lg border px-3 py-2 font-bold text-primary-700"><FontAwesomeIcon icon={faEye}/> Review</button></td></tr>})}</tbody></table></div>}</div>
  {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-7 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary-600">{tab==='industry'?'Industry partner review':'Buyer verification'}</p><h2 className="mt-1 text-2xl font-black">{tab==='industry'?selected.organization_name:selected.full_name||selected.email}</h2></div><button onClick={()=>setSelected(null)}><FontAwesomeIcon icon={faXmark}/></button></div><div className="mt-6 grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2">{Object.entries(tab==='industry'?{Email:selected.profile?.email,Phone:selected.business_phone,Type:selected.organization_type,Location:[selected.city,selected.state].filter(Boolean).join(', '),GST:selected.gst_number,Udyam:selected.udyam_number,'Profile completion':`${selected.profile_completion||0}%`,'Documents':selected.industry_member_documents?.length||0}:{Email:selected.email,Phone:selected.phone,Company:selected.company_name,Location:[selected.city,selected.state].filter(Boolean).join(', '),'Account status':selected.account_status,'Registered':new Date(selected.created_at).toLocaleString('en-IN')}).map(([key,value])=><div key={key}><dt className="text-xs font-bold uppercase text-slate-400">{key}</dt><dd className="mt-1 font-semibold text-slate-800">{value||'—'}</dd></div>)}</div>{tab==='industry'&&<><h3 className="mt-6 font-black">Capabilities</h3><div className="mt-2 flex flex-wrap gap-2">{[...(selected.product_categories||[]),...(selected.materials||[]),...(selected.techniques||[])].map(x=><span key={x} className="rounded-full bg-primary-50 px-3 py-1 text-xs font-bold text-primary-700">{x}</span>)}</div></>}<div className="mt-7 flex flex-wrap justify-end gap-2"><button disabled={busy} onClick={()=>review('under_review')} className="rounded-xl border px-4 py-2 font-bold">Mark under review</button><button disabled={busy} onClick={()=>review('rejected')} className="rounded-xl border border-red-200 px-4 py-2 font-bold text-red-600">Reject</button><button disabled={busy} onClick={()=>review('suspended')} className="rounded-xl bg-slate-800 px-4 py-2 font-bold text-white">Suspend</button><button disabled={busy} onClick={()=>review('verified')} className="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white"><FontAwesomeIcon icon={faCheck}/> Verify</button></div></div></div>}</div>;
}
